<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
    <div class="newproducts">
        <div class="carousel">
            <div class="slider">
                <?php $i=0; foreach ($_products->getItems() as $_product): $i++; ?>
                    <?php if($i > themeOptions('new_carousel_limit')) { break; } ?>
                    <div class="item slide <?php if(($i == 4 && $_products->getSize() < 5) || ($i == $_products->getSize()) ) echo 'last'?>"> 
                        <?php include('view/labels.phtml')  ?>

                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        
<div class="box-product-item">
<div class="box-product-buttons">
    <div class="buttons-compare" onclick="setLocation('<?php echo $this->getAddToCompareUrl($_product) ?>')"></div>
    <div class="buttons-wish" onclick="setLocation('<?php echo $this->getAddToWishlistUrl($_product) ?>')"></div>
</div>
<div class="box-line"></div>
<div class="view-first">

<div class="view-content">

<div class="image">
<a href="<?php echo $_product->getProductUrl() ?>">
<img alt="<?php echo $this->htmlEscape($_product->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(225,255) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>"">
</a>
</div>
<div class="name">
<?php

 $shortenby = themeOptions('shorten_name');

 $product_name = $this->htmlEscape($_product->getName());

 mb_internal_encoding("UTF-8");
  
 if(strlen($product_name) > $shortenby) { $product_name = mb_substr($product_name,0,$shortenby).'...'; }
?>
<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $product_name ?></a>
</div>

<div class="buttons-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"></div>

    

<div class="price">
    
<?php echo $this->getPriceHtml($_product, true) ?>
    
</div>

</div>


</div>
</div>
                      
                    </div>
                <?php endforeach; ?>
            </div>             
        </div>
        <?php if($_products->getSize() > 1): ?>
            <div class="prev new-arrow"></div>
            <div class="next new-arrow"></div>  
        <?php endif; ?>
    </div>     
    <div class="clear"></div>
    <?php if($_products->getSize() > 1): ?>
    <?php if(themeOptions('new_carousel')): ?>
	<style type="text/css">
            .new-arrow {
                display:block;
            }
            .newproducts .carousel {
                height:344px;
            }
            .newproducts .slide {
                margin-bottom:0px;
            }
        </style>
	<script type="text/javascript">
        
            jQuery('.new-arrow.prev').addClass('disabled');
            jQuery('.newproducts .carousel').iosSlider({
                desktopClickDrag: true,
                snapToChildren: true,
                infiniteSlider: false,
                navNextSelector: '.new-arrow.next',
                navPrevSelector: '.new-arrow.prev',
                lastSlideOffset: 3,
                onFirstSlideComplete: function(){
                    jQuery('.new-arrow.prev').addClass('disabled');
                },
                onLastSlideComplete: function(){
                    jQuery('.new-arrow.next').addClass('disabled');
                },
                onSlideChange: function(){
                    jQuery('.new-arrow.prev').removeClass('disabled');
                    jQuery('.new-arrow.next').removeClass('disabled');
                }
            });
         
       
        </script> 
		
    <?php endif; ?>
           
    <?php endif; ?>
<?php endif; ?>